"""empty message

Revision ID: 402750afb443
Revises: b8e29fd26499
Create Date: 2023-09-17 17:31:13.359484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402750afb443'
down_revision = 'b8e29fd26499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
