"""empty message

Revision ID: 4cfc9cf622fa
Revises: 3a24db4917c4
Create Date: 2023-09-18 14:06:10.803033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cfc9cf622fa'
down_revision = '3a24db4917c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activate_tag', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('activate_tag')

    # ### end Alembic commands ###
