"""empty message

Revision ID: b6157557ceaf
Revises: c13cde81f6b4
Create Date: 2023-09-19 22:25:07.877111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6157557ceaf'
down_revision = 'c13cde81f6b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('funds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_name', sa.String(length=255), nullable=True),
    sa.Column('goal', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaults')
    op.drop_table('users')
    # ### end Alembic commands ###
