"""empty message

Revision ID: c13cde81f6b4
Revises: 2c7c24d25b69
Create Date: 2023-09-18 16:31:46.900095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13cde81f6b4'
down_revision = '2c7c24d25b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_amount', sa.Integer(), nullable=True))
        batch_op.drop_column('budget')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('budget_amount')

    # ### end Alembic commands ###
